-- Initial migration
CREATE TABLE IF NOT EXISTS metrics (
  id INT AUTO_INCREMENT PRIMARY KEY,
  service VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  response_time_ms DOUBLE NULL,
  error_rate DOUBLE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  service VARCHAR(128) NOT NULL,
  level VARCHAR(32) NOT NULL,
  message VARCHAR(512) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
